### ISSUE TITLE
is it safe call sqlite3_key when other threads reading on the same db 

### ISSUE THREAD

**Issue by Vincentzzg** [sqlcipher/sqlcipher#381] opened 2021-02-22 02:52 UTC
### Expected Behavior
Concurrent reads should not crash
### Actual Behavior
crash
### Steps to Reproduce
[CTPersistance](https://github.com/casatwy/CTPersistance) is a package library based on sqlcipher.
Use [CTPersistance](https://github.com/casatwy/CTPersistance)  and run this Unit Test 
[CTPersistanceTestConcurrentRead.m.zip](https://github.com/sqlcipher/sqlcipher/files/6019231/CTPersistanceTestConcurrentRead.m.zip)（Drag it to the CTPersistanceTests directory）
 several times，you will see the crash. Every read crash is accompanied by a call to sqlite3_key. And I have reproduced it many times.

Crash screenshot：
<img width="1507" alt="107120083-7626ce00-68c6-11eb-8655-f581c3d08f6b" src="https://user-images.githubusercontent.com/10241716/108651037-e73bc780-74fb-11eb-94bb-02526301235c.png">
<img width="1027" alt="107120106-9e163180-68c6-11eb-9fcf-7f103883d0bd" src="https://user-images.githubusercontent.com/10241716/108651047-eacf4e80-74fb-11eb-995f-7b13cb2fe5ef.png">

SQLCipher version:
SQLCipher 4.4.0

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by sjlombardo** [comment] 2021-02-23 20:08
Hello @Vincentzzg I have attempted to run that test a dozen times with CTPersistance but have not been able to reproduce a crash. 

That said, with regard to your questions:

1. It is safe to call sqlite3_key on one database handle (i.e. the sqlite3 * returned from sqlite3_open) while another thread using a separate handle for the same database file. In other words, if each thread has it's own database connection this is safe. 
2. It is not safe to repeatedly call sqlite3_key on a database handles across multiple threads. The sqlite3_key execution should occur exactly once following sqlite3_open.  Repeated invocations could definitely cause problems and furthermore would be horribly slow due to repeated invocation of expensive key derivation operations. Applications using a single database connection simultaneously in multiple threads should ensure that the database is "keyed" exactly one time before use (in the same way they would ensure that sqlite3_open is only called once). 

Since I am not familiar with CTPersistence, and I can't reproduce the crash it's difficult to say what is going on here. However, I suspect that sqlite3_key might be called multiple times (case 2 above) resulting in the reallocation of the internal context while it is being used in another thread.

**Comment by Vincentzzg** [comment] 2021-02-24 02:13
The failure to reproduce the crash may be because the author added a synchronization lock to control concurrency in the latest submission.

To reproduce the crash, you need to use an earlier code submission.
You can try it with submit 65921d938314aeab7dd8642556a85f196c114e6a. This submission contains test cases for concurrent testing.
I am using a real iPhone xs device to reproduce the bug.The key point is to use equipment with poor performance to ensure the possibility of simultaneous execution.

**Comment by sjlombardo** [comment] 2021-03-04 15:38
@Vincentzzg thanks for the update. Since it sounds like this issue was resolved in the CTPersistance project I'll close this ticket for now.

**Closed by sjlombardo** 2021-03-04 15:38 UTC

**Comment by Vincentzzg** [comment] 2021-03-23 08:21
I'm so sorry that I haven't responded for so long, but the problem has not been resolved.

The changes in the CTPersistance project only reduce the probability of a crash. These modifications make it difficult to reproduce the crash, but the nature of the problem has not changed.

Same as before：
To reproduce the crash, you need to use an earlier code submission [65921d938314aeab7dd8642556a85f196c114e6a](https://github.com/casatwy/CTPersistance/tree/65921d938314aeab7dd8642556a85f196c114e6a). 
After opening the page, click the ’Code‘ button on the page, then click ’Download ZIP‘, and then execute ’pod install‘ to build the complete project. Finally, run the project and execute the testConcurrentRead method in the CTPersistanceTestConcurrentRead.m file.
The problem may not be reproduced every time, it may take several attempts.



Below is the crash log in my project：
[resultv1_1.log](https://github.com/sqlcipher/sqlcipher/files/6187909/resultv1_1.log)

This is just one of many crashes. All crashes are performed while a read operation is performed while another thread is executing the sqlite3_key function.

**Comment by sjlombardo** [comment] 2021-03-23 13:20
Hello @Vincentzzg thanks for following up on this. Given that this is still a problem I think this ticket really needs to be raised separately with the CTPersistance project. The library should not be repeatedly calling `sqlite3_key` on a database handle at all, let alone one that is being used in a separate thread. The CTPersistance library must refactored to call `sqlite3_key` a single time following `sqlite3_open`.
