### ISSUE TITLE
fatal error: 'editline/readline.h' file not found when building/linking iPhone targets 

### ISSUE THREAD

**Issue by bgalamb** [sqlcipher/sqlcipher#294] opened 2018-12-05 08:34 UTC
### Expected Behavior

"./make" finish successfull

### Actual Behavior

libtool: link: gcc -DSQLITE_HAS_CODEC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/ -fno-common -arch armv7s -DSQLCIPHER_CRYPTO_CC -DSQLITE_OS_UNIX=1 -I. -I/Users/i040023/tmp/sqlcipher/src -I/Users/i040023/tmp/sqlcipher/ext/rtree -I/Users/i040023/tmp/sqlcipher/ext/icu -I/Users/i040023/tmp/sqlcipher/ext/fts3 -I/Users/i040023/tmp/sqlcipher/ext/async -I/Users/i040023/tmp/sqlcipher/ext/session -D_HAVE_SQLITE_CONFIG_H -DBUILD_sqlite -DNDEBUG -DSQLITE_THREADSAFE=1 -DSQLITE_HAVE_ZLIB=1 -DHAVE_READLINE=0 -DHAVE_EDITLINE=1 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_EXPLAIN_COMMENTS -DSQLITE_ENABLE_UNKNOWN_SQL_FUNCTION -DSQLITE_ENABLE_STMTVTAB -DSQLITE_ENABLE_DBPAGE_VTAB -DSQLITE_ENABLE_DBSTAT_VTAB -DSQLITE_ENABLE_OFFSET_SQL_FUNC -DSQLITE_INTROSPECTION_PRAGMAS -o .libs/sqlcipher shell.c  ./.libs/libsqlcipher.dylib -ledit -lz -framework Foundation -framework Security
shell.c:119:11: fatal error: 'editline/readline.h' file not found
# include <editline/readline.h>
          ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [sqlcipher] Error 1

Even though the file ./.libs/lisqlcipher.a is there and has the correct architecture in it. (checked with lipo)

On the other hand build it for macOs target it is successfull. 
It looks like the libraries being linked are not available for Phone (iPhone, IphoneSimulator) targets
see:
./usr/local/Cellar/readline/7.0.3_1/include/readline/readline.h
./Applications/Xcode.app/Contents/Developer/Platforms/**MacOSX.platform**/Developer/SDKs/MacOSX.sdk/usr/include/editline/readline.h
./Applications/Xcode.app/Contents/Developer/Platforms/**MacOSX.platform**/Developer/SDKs/MacOSX.sdk/usr/include/readline/readline.h

### Steps to Reproduce

Download latest released version (4.0.0)
Configure the build to build for iPhone target, arm64
execute command : 
arm64

1. 

./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC -mios-version-min=10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/ -fno-common -arch arm64" --with-crypto-lib=commoncrypto LDFLAGS="-framework Security -framework Foundation" --host=arm-apple-darwin

configure is successfull

2. 
execute
./make

SQLCipher version:

latest released version (4.0.0)

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by sjlombardo** [comment] 2018-12-05 16:04
Hello @bgalamb - Thanks for the report about SQLCipher! We tried the build approach you mentioned here with the SQLite 3.25.2 source release, without the SQLCipher-specific flags, and the same error occurs. This means that the issue is present in the upstream SQLite version that SQLCipher is based on. 

As a matter of policy we avoid making changes to SQLCipher that would create conflicts with SQLite, and we generally don't support build methods that don't work with SQLite itself. 

One suggestion would be to try a different supported integration approach for SQLCipher, e.g. including the sqlite3.c amalgamation directly in your project or using CocoaPods. 

If that is not feasible for some reason and you really want to build this way then you could consider submitting a patch to the SQLite project that would fix the problem (again, without the SQLCipher flags). That way once the root cause was fixed upstream in SQLite it would merge into a future release of SQLCipher the next time we rebase.

**Comment by bgalamb** [comment] 2018-12-06 14:22
Hi
I think the cause of this might be that the command line utility that it tries to build is N/A for phones.

Executing make for the following target solved the issue: 

`./make libsqlcipher.la`

**Comment by sjlombardo** [comment] 2018-12-19 14:00
It sounds like this issue has a simple workaround, so I'll close this for now.

**Closed by sjlombardo** 2018-12-19 14:00 UTC
