### ISSUE TITLE
ROLLBACK TO SAVEPOINT stmt within committed transaction cause write operation to the WAL file.

### ISSUE THREAD

**Issue by RingoD** [sqlcipher/sqlcipher#302] opened 2019-01-04 01:17 UTC
### Expected Behavior
No write operation happen on WAL file if all savepoints rollbacked within a committed transaction 

### Actual Behavior
WAL file will be enlarged even if nothing to write.

### Steps to Reproduce
```
sqlcipher db

// Preparation
PRAGMA journal_mode=WAL;
CREATE TABLE t(i INTEGER);
INSERT INTO t VALUES(1);
PRAGMA wal_checkpoint=TRUNCATE;

// check the WAL file size without checkpoint/close sqlite connection
ls -l | grep wal
// print 0 db-wal

// It's a no-op which is expected to cause no write operation. BUT IT DID.
BEGIN IMMEDIATE;
SAVEPOINT s1;
INSERT INTO t VALUES(2);
ROLLBACK TO SAVEPOINT s1;
COMMIT; // I know it should be ROLLBACK instead COMMIT. But it's for demo only here. In my case, it must be COMMIT to submit other operations outside the SAVEPOINT.

SELECT * FROM t;
// print 1, which means that nothing changed in the database.

// check the WAL file size without checkpoint/close sqlite connection
ls -l | grep wal
// EXPECT "0 db-wal" since there is nothing changed on the database.
// print 4152 db-wal. 
```

SQLCipher version:
```
$ sqlcipher --version
3.20.1 2017-08-24 16:21:36 8d3a7ea6c5690d6b7c3767558f4f01b511c55463e3f9e64506801fe9b74dce34
```

**Comment by sjlombardo** [comment] 2019-01-04 13:45
Hello @RingoD - I just tested this with the standard SQLite release 3.26.0 and observed the same exact results. This implies that this is not an issue or a regression with SQLCipher itself, but the behavior of SQLite itself. Have your reported this issue to the SQLite development team?

**Comment by groue** [comment] 2019-01-04 13:57
Quoting https://www.sqlite.org/wal.html:

> **How WAL Works**
>
> The traditional rollback journal works by writing a copy of the original unchanged database content into a separate rollback journal file and then writing changes directly into the database file. [...] The WAL approach inverts this. The original content is preserved in the database file and the changes are appended into a separate WAL file.

This means that changes that are not yet rollbacked are appended to the wal file. It is normal that the wal file becomes non empty during your transaction.

But is it normal that the wal file remains non empty after the transaction is rollbacked?

Yes it is, too, because **checkpointing** (the operation that transfers all WAL information into the main database file) does not happen automatically until the wal file has reached a certain size. For more information, proceed to the reference: https://www.sqlite.org/wal.html

**Comment by RingoD** [comment] 2019-01-07 02:04
@sjlombardo  Yes, I send the same issue to mail list of SQLite: sqlite-users@mailinglists.sqlite.org.
Sadly, there's no one reply. So I ask for your help, or do you have any more high priority feedback channel?

**Comment by RingoD** [comment] 2019-01-07 02:07
@groue  You are right. The main database file will not changed after checkpointing. 
But I am concerned about this because the performance. I have a "try and rollback to savepoint" logic in my code. So I want it have no write operation happen by those rolled back savepoint. Otherwise, my "try and rollback to savepoint" is meaningless.

**Comment by sjlombardo** [comment] 2019-02-12 21:53
Hello @RingoD  - I don't think there is anything else we can do to help here, since this is the behavior of SQLite upstream. I'm not even sure there is a performance issue at play here either, it's just how WAL works. As such, I'm going to close this for now. 

P.S. Thank you for chiming in on this ticket as well @groue!

**Closed by sjlombardo** 2019-02-12 21:53 UTC
