### ISSUE TITLE
Compile problem " unknown type name ‘sqlite3_mutex’ "

### ISSUE THREAD

**Issue by lemonahmas** [sqlcipher/sqlcipher#359] opened 2020-03-15 04:51 UTC
### Expected Behavior
Correctly built.

### Actual Behavior
 error: unknown type name ‘sqlite3_mutex’
 sqlite3_mutex* sqlcipher_mutex(int);
 ^~~~~~~~~~~~~
Makefile:819: recipe for target 'crypto.lo' failed
make: *** [crypto.lo] Error 1

### Steps to Reproduce
When trying to build in WSL, have sqlite3 pre-installed, configured as shown in README, make.

SQLCipher version:
Current.
*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by sjlombardo** [comment] 2020-03-16 16:15
There is not enough information here to determine what is going wrong. That said, this really like a build environment issue. You should consider posting to the discussion site: https://discuss.zetetic.net/c/sqlcipher

**Comment by lemonahmas** [comment] 2020-03-16 16:21
> There is not enough information here to determine what is going wrong. That said, this really like a build environment issue. You should consider posting to the discussion site: https://discuss.zetetic.net/c/sqlcipher

I downloaded the archived version, which is V4.3.0, built in the exact same env, and it worked. Sadly it looks like a bug. If you guys need any further information to locate it, I'm glad to help.

**Comment by sjlombardo** [comment] 2020-03-16 16:37
What version were you building before, and what do you mean by the archived version?

**Comment by lemonahmas** [comment] 2020-03-17 01:21
The code I was building first is cloned from the master branch directly, and by "archived version" I mean the latest release. Sorry for the misdirection.

**Comment by sjlombardo** [comment] 2020-03-17 14:55
@lemonahmas that is very unusual. The master branch and v4.3.0 tag are identical (same commit).

**Comment by lemonahmas** [comment] 2020-03-18 00:30
> @lemonahmas that is very unusual. The master branch and v4.3.0 tag are identical (same commit).

Indeed they are both at ece66fd. But in this commit, I found some changes about mutex so maybe it's a merge issue? (or not)
Anyways, thank you for your support.

**Comment by egorpugin** [comment] 2020-03-18 16:28
Same for me on win+vs2019 16.5.
Quick patching like this
```
        sqlcipher.pushFrontToFileOnce("src/crypto.c", "#include <sqlite3.h>");
        sqlcipher.pushFrontToFileOnce("src/crypto_impl.c", "#include <sqlite3.h>");
        sqlcipher.pushFrontToFileOnce("src/crypto_openssl.c", "#include <sqlite3.h>\n#include \"sqlcipher.h\"");
```

All three files have missing headers or wrong order or whatever. It's up to you.

**Comment by sjlombardo** [comment] 2020-05-13 14:27
We've been unable to reproduce any issues, and have cross checked the source. Since the current release is now v4.4.0 I'm going to close this.

**Closed by sjlombardo** 2020-05-13 14:27 UTC
