### ISSUE TITLE
Fail to clone repo

### ISSUE THREAD

**Issue by Giszmo** [sqlcipher/sqlcipher#461] opened 2022-12-30 01:07 UTC
### Expected Behavior

```
$ git clone https://github.com/sqlcipher/sqlcipher
$
```

works

### Actual Behavior

```
$ git clone https://github.com/sqlcipher/sqlcipher
Cloning into 'sqlcipher'...
remote: Enumerating objects: 15498, done.
remote: Counting objects: 100% (1910/1910), done.
remote: Compressing objects: 100% (816/816), done.
error: object e35e28f52d20df27561b2780f6b9c86669a9de21: zeroPaddedFilemode: contains zero-padded file modes
fatal: fsck error in packed object
fatal: index-pack failed
```

**Comment by Giszmo** [comment] 2022-12-30 06:33
Apparently I did enable the fsck years ago in my git but this repo being the first in many hundreds I cloned to show this error makes me assume the issue is not out of place.

**Comment by developernotes** [comment] 2022-12-30 14:05
Hi @Giszmo,

I suspect the issue is local to your system. What version of `git` do you have installed?

```
✓ nparker@work:/tmp $ git clone https://github.com/sqlcipher/sqlcipher
Cloning into 'sqlcipher'...
remote: Enumerating objects: 15498, done.
remote: Counting objects: 100% (1910/1910), done.
remote: Compressing objects: 100% (807/807), done.
remote: Total 15498 (delta 1107), reused 1824 (delta 1087), pack-reused 13588
Receiving objects: 100% (15498/15498), 46.13 MiB | 7.83 MiB/s, done.
Resolving deltas: 100% (10616/10616), done.
✓ nparker@work:/tmp $ git --version
git version 2.39.0
```

**Comment by Giszmo** [comment] 2022-12-30 19:01
Try out `git fsck` in your repo. I enabled this for all clone/fetch operations by default and never had a problem with other repos.

I didn't dig into what exactly the error means but caring about security I'd want to either understand why it's harmless or see it fixed.

**Comment by sjlombardo** [comment] 2022-12-30 21:16
We can confirm this with `git fsck`. Unfortunately, this doesn't look like it can be easily fixed without [rebuilding](https://gitlab.com/gitlab-org/gitaly/-/issues/2889) [the](https://stackoverflow.com/questions/14700502/how-to-fix-git-zero-padded-file-modes-warning) [repo](https://github.com/pallets/flask/pull/2057/files) which would alter history (change SHAs). There are thousands of clones of this project out here, so we wish to avoid doing that. Thus, you will need to work around this while cloning. 

The following post has some options for doing so, e.g., disabling `fsck` during clone, setting `fsck.zeroPaddedFilemode=ignore`, shallow cloning, etc.:

https://stackoverflow.com/questions/41029654/ignore-fsck-zero-padded-file-mode-errors-in-git-clone

**Closed by sjlombardo** 2022-12-30 21:16 UTC

**Comment by Giszmo** [comment] 2022-12-30 22:14
Thank you for your pointers. I only wonder what relevance the error has for the integrity of the project. Will figure it out ...
