### ISSUE TITLE
4.4.2: compile time warnings

### ISSUE THREAD

**Issue by kloczek** [sqlcipher/sqlcipher#380] opened 2021-02-01 15:33 UTC
gcc 11.0.1
Compile time wrnings:
```
sqlite3.c:119216:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
119216 |   if( pIdx->pPartIdxWhere!=0 ) x -= 10;  assert( 10==sqlite3LogEst(2) );
       |   ^~
In file included from sqlite3.c:14181:
sqlite3.c:119216:42: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
119216 |   if( pIdx->pPartIdxWhere!=0 ) x -= 10;  assert( 10==sqlite3LogEst(2) );
       |                                          ^~~~~~
At top level:
sqlite3.c:64031:20: warning: 'sqlite3PagerState' defined but not used [-Wunused-function]
64031 | SQLITE_PRIVATE int sqlite3PagerState(Pager *pPager){
      |                    ^~~~~~~~~~~~~~~~~
sqlite3.c: In function 'sqlite3DefaultRowEst':
sqlite3.c:119216:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
119216 |   if( pIdx->pPartIdxWhere!=0 ) x -= 10;  assert( 10==sqlite3LogEst(2) );
       |   ^~
In file included from sqlite3.c:14181:
sqlite3.c:119216:42: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
119216 |   if( pIdx->pPartIdxWhere!=0 ) x -= 10;  assert( 10==sqlite3LogEst(2) );
       |                                          ^~~~~~
At top level:
sqlite3.c:64031:20: warning: 'sqlite3PagerState' defined but not used [-Wunused-function]
64031 | SQLITE_PRIVATE int sqlite3PagerState(Pager *pPager){
      |                    ^~~~~~~~~~~~~~~~~
libtool: warning: remember to run 'libtool --finish /usr/lib64'
```
Additionally some warnings in test suite (that parts whic are not affected by #379). Some of them are exposed by using LTO.
```
sqlite3.c: In function 'sqlite3DefaultRowEst':
sqlite3.c:119216:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
119216 |   if( pIdx->pPartIdxWhere!=0 ) x -= 10;  assert( 10==sqlite3LogEst(2) );
       |   ^~
In file included from sqlite3.c:14181:
sqlite3.c:119216:42: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
119216 |   if( pIdx->pPartIdxWhere!=0 ) x -= 10;  assert( 10==sqlite3LogEst(2) );
       |                                          ^~~~~~
At top level:
sqlite3.c:64031:20: warning: 'sqlite3PagerState' defined but not used [-Wunused-function]
64031 | SQLITE_PRIVATE int sqlite3PagerState(Pager *pPager){
      |                    ^~~~~~~~~~~~~~~~~
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/11/../../../../lib64/crt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [<builtin>: sqlite3] Error 1
make: *** Waiting for unfinished jobs....
/home/tkloczko/rpmbuild/BUILD/sqlcipher-4.4.2/tool/sqldiff.c: In function 'all_tables_sql':
/home/tkloczko/rpmbuild/BUILD/sqlcipher-4.4.2/tool/sqldiff.c:1795:9: warning: variable 'rc' set but not used [-Wunused-but-set-variable]
 1795 |     int rc;
      |         ^~
sqlite3_analyzer.c: In function 'sqlite3DefaultRowEst':
sqlite3_analyzer.c:119240:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
119240 |   if( pIdx->pPartIdxWhere!=0 ) x -= 10;  assert( 10==sqlite3LogEst(2) );
       |   ^~
In file included from sqlite3_analyzer.c:14205:
sqlite3_analyzer.c:119240:42: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
119240 |   if( pIdx->pPartIdxWhere!=0 ) x -= 10;  assert( 10==sqlite3LogEst(2) );
       |                                          ^~~~~~
At top level:
sqlite3_analyzer.c:64055:20: warning: 'sqlite3PagerState' defined but not used [-Wunused-function]
64055 | SQLITE_PRIVATE int sqlite3PagerState(Pager *pPager){
      |                    ^~~~~~~~~~~~~~~~~
sqlite3_analyzer.c:24338:13: warning: 'sqlcipher_profile_callback' defined but not used [-Wunused-function]
24338 | static void sqlcipher_profile_callback(void *file, const char *sql, sqlite3_uint64 run_time){
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
sqltclsh.c: In function 'sqlite3DefaultRowEst':
sqltclsh.c:119252:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
119252 |   if( pIdx->pPartIdxWhere!=0 ) x -= 10;  assert( 10==sqlite3LogEst(2) );
       |   ^~
In file included from sqltclsh.c:14217:
sqltclsh.c:119252:42: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
119252 |   if( pIdx->pPartIdxWhere!=0 ) x -= 10;  assert( 10==sqlite3LogEst(2) );
       |                                          ^~~~~~
At top level:
sqltclsh.c:64067:20: warning: 'sqlite3PagerState' defined but not used [-Wunused-function]
64067 | SQLITE_PRIVATE int sqlite3PagerState(Pager *pPager){
      |                    ^~~~~~~~~~~~~~~~~
sqltclsh.c:24350:13: warning: 'sqlcipher_profile_callback' defined but not used [-Wunused-function]
24350 | static void sqlcipher_profile_callback(void *file, const char *sql, sqlite3_uint64 run_time){
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/tkloczko/rpmbuild/BUILD/sqlcipher-4.4.2/test/sessionfuzz.c:67:
./sqlite3.c: In function 'sqlite3DefaultRowEst':
./sqlite3.c:119216:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
119216 |   if( pIdx->pPartIdxWhere!=0 ) x -= 10;  assert( 10==sqlite3LogEst(2) );
       |   ^~
In file included from ./sqlite3.c:14181,
                 from /home/tkloczko/rpmbuild/BUILD/sqlcipher-4.4.2/test/sessionfuzz.c:67:
./sqlite3.c:119216:42: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
119216 |   if( pIdx->pPartIdxWhere!=0 ) x -= 10;  assert( 10==sqlite3LogEst(2) );
       |                                          ^~~~~~
At top level:
/home/tkloczko/rpmbuild/BUILD/sqlcipher-4.4.2/test/sessionfuzz.c:70:19: warning: 'zInitSql' defined but not used [-Wunused-const-variable=]
   70 | static const char zInitSql[] =
      |                   ^~~~~~~~
In file included from /home/tkloczko/rpmbuild/BUILD/sqlcipher-4.4.2/test/sessionfuzz.c:67:
./sqlite3.c:64031:20: warning: 'sqlite3PagerState' defined but not used [-Wunused-function]
64031 | SQLITE_PRIVATE int sqlite3PagerState(Pager *pPager){
      |                    ^~~~~~~~~~~~~~~~~
sqlite3.c: In function 'sqlite3DefaultRowEst':
sqlite3.c:119216:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
119216 |   if( pIdx->pPartIdxWhere!=0 ) x -= 10;  assert( 10==sqlite3LogEst(2) );
       |   ^~
In file included from sqlite3.c:14181:
sqlite3.c:119216:42: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
119216 |   if( pIdx->pPartIdxWhere!=0 ) x -= 10;  assert( 10==sqlite3LogEst(2) );
       |                                          ^~~~~~
At top level:
sqlite3.c:64031:20: warning: 'sqlite3PagerState' defined but not used [-Wunused-function]
64031 | SQLITE_PRIVATE int sqlite3PagerState(Pager *pPager){
      |                    ^~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/sqlcipher-4.4.2/src/test1.c: In function 'file_control_test':
/home/tkloczko/rpmbuild/BUILD/sqlcipher-4.4.2/src/test1.c:5830:7: warning: variable 'rc' set but not used [-Wunused-but-set-variable]
 5830 |   int rc;
      |       ^~
/home/tkloczko/rpmbuild/BUILD/sqlcipher-4.4.2/src/test1.c: In function 'save_prng_state':
/home/tkloczko/rpmbuild/BUILD/sqlcipher-4.4.2/src/test1.c:6402:7: warning: variable 'rc' set but not used [-Wunused-but-set-variable]
 6402 |   int rc = sqlite3_test_control(9999);
      |       ^~
/home/tkloczko/rpmbuild/BUILD/sqlcipher-4.4.2/src/test_journal.c: In function 'readJournalFile':
/home/tkloczko/rpmbuild/BUILD/sqlcipher-4.4.2/src/test_journal.c:487:19: warning: unused variable 'cksum' [-Wunused-variable]
  487 |               u32 cksum = genCksum(aPage, pMain->nPagesize);
      |                   ^~~~~
/home/tkloczko/rpmbuild/BUILD/sqlcipher-4.4.2/src/test_journal.c: In function 'jtWrite':
/home/tkloczko/rpmbuild/BUILD/sqlcipher-4.4.2/src/test_journal.c:557:11: warning: unused variable 'pgno' [-Wunused-variable]
  557 |       u32 pgno = (u32)(iOfst/p->nPagesize + 1);
      |           ^~~~
/home/tkloczko/rpmbuild/BUILD/sqlcipher-4.4.2/src/test_journal.c: In function 'jtTruncate':
/home/tkloczko/rpmbuild/BUILD/sqlcipher-4.4.2/src/test_journal.c:589:9: warning: unused variable 'locking_page' [-Wunused-variable]
  589 |     u32 locking_page = (u32)(PENDING_BYTE/p->nPagesize+1);
      |         ^~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/sqlcipher-4.4.2/src/test_pcache.c: In function 'testpcacheCachesize':
/home/tkloczko/rpmbuild/BUILD/sqlcipher-4.4.2/src/test_pcache.c:169:15: warning: unused variable 'p' [-Wunused-variable]
  169 |   testpcache *p = (testpcache*)pCache;
      |               ^
sqlite3.c: In function 'sqlite3UtfSelfTest':
sqlite3.c:36302:16: warning: variable 'c' set but not used [-Wunused-but-set-variable]
36302 |   unsigned int c;
      |                ^
sqlite3.c:36301:7: warning: variable 'n' set but not used [-Wunused-but-set-variable]
36301 |   int n;
      |       ^
sqlite3.c:36298:19: warning: variable 't' set but not used [-Wunused-but-set-variable]
36298 |   unsigned int i, t;
      |                   ^
sqlite3.c: In function 'sqlite3DefaultRowEst':
sqlite3.c:119216:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
119216 |   if( pIdx->pPartIdxWhere!=0 ) x -= 10;  assert( 10==sqlite3LogEst(2) );
       |   ^~
In file included from sqlite3.c:14181:
sqlite3.c:119216:42: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
119216 |   if( pIdx->pPartIdxWhere!=0 ) x -= 10;  assert( 10==sqlite3LogEst(2) );
       |                                          ^~~~~~
/
```

**Comment by sjlombardo** [comment] 2021-03-08 19:06
Hello @kloczek - thanks for submitting this issue. I have gone through the warnings here and isolated a few that were being caused by of SQLCipher's code extensions. These have been resolved in the recent 4.4.3 release. 

That said, the majority of these warnings are actually stemming from core SQLite code. We try hard to avoid making changes to SQLCipher that would cause conflicts with SQLite upstream merges. As a result, we wouldn't make any further changes. 

If you were interested in bringing these issues to the attention of the SQLite team, our recommendation would be to eliminate SQLCipher from the equation entirely. Start with a fresh copy of the latest version of SQLite, and then determine the list of warnings that you feel should be addressed. You could the consider submitting requests or patches the [SQLite forum](https://www.sqlite.org/support.html). If the changes are applied to a release version of SQLite the would then find their way back into SQLCipher when we merge. 

I will mark this ticket as closed for now.

**Closed by sjlombardo** 2021-03-08 19:06 UTC
